name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    # Needed by release action
    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else
        run: |
          set -e
          sudo apt install zstd
          python -m venv venv
          source venv/bin/activate
          python -m pip install matplotlib pandas numpy
          python ./makegraphs.py
          set +e

      - name: Make release
        run: |
          set -e
          tagname=$(git describe --tags --abbrev=0)
          mv "output" "graphs-${tagname}"
          tar cf - "graphs-${tagname}" | zstd --compress --ultra -20 --threads=0 - -o "graphs-${tagname}.tar.zst"
          mv "graphs-${tagname}" "output"
          ls -lah
          set +e
        
        # FIXME there's probably a code injection
        # vuln somewhere in these horrible shards of shell code,
        # but oh well, let's just say we trust
        # whoever has push access to this repo

      - name: Upload release artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.zst"

